### ISSUE TITLE
Create feature list purchase orders

### ISSUE THREAD

**Issue by dfontoura** [dfontoura/knowledge-test#1]
- Create endpoint **/orders** to receive GET request;
- The list must contain all the purchase order data, as well as the supplier and product data;
- Handle exceptions

### To-do List:

- [ ] Create orders repository
- [ ] Create findAllOrders controller
- [ ] Create factory for findAllOrdersController
- [ ] Create tests
- [ ] Create route for **/orders** GET requests
