### ISSUE TITLE
Create feature insert purchase orders

### ISSUE THREAD

**Issue by dfontoura** [dfontoura/knowledge-test#2]
- Expose endpoint **/orders** to receive POST request;
- Must accept the creation of one or more orders at the same request;
- Validate product_id and price fields;
- Handle exceptions.

### To-do List:

- [ ] update orders repository
- [ ] update findAllOrders controller
- [ ] update factory for findAllOrdersController
- [ ] Create tests
- [ ] Create route for **/orders** POST requests
